### ISSUE TITLE
Drops with Moxy library

### ISSUE THREAD

**Issue by tseglevskiy** [arturdm/jacoco-android-gradle-plugin#28]
I've added MVP implementation by Moxy library. Task `:sample-app:jacocoTestFreeDebugUnitTestReport` drops:

`Caused by: java.io.FileNotFoundException: /Users/tse/jd/tmp/example-android/sample-app/build/intermediates/classes/free/debug/com/dicedmelon/example/android/MainActivity$PresentersBinder$presenterBinder.class (No such file or directory)
        at org.apache.tools.ant.types.resources.FileResource.getInputStream(FileResource.java:217)
        at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:569)
        at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
        at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
        ... 83 more`

I can find the following classes:

`maaaacy:example-android $ find . | grep presenterBinder
./sample-app/build/intermediates/classes/free/debug/com/dicedmelon/example/android/MainActivity$$PresentersBinder$presenterBinder.class
./sample-app/build/intermediates/transforms/jacoco/free/debug/folders/1/1/main/com/dicedmelon/example/android/MainActivity$$PresentersBinder$presenterBinder.class
maaaacy:example-android $`

There is a difference in `$$` in the class name.

The project: https://github.com/tseglevskiy/example-android

Is it a bug?

**Comment by tseglevskiy** [comment]
In test project I excluded autogenerated classes, and it helps:

`                    '**/*$PresentersBinder$*.class',
                    '**/*$PresentersBinder.class',
                    '**/*$ViewStateProvider.class',
                    '**/*$State$*.class',
                    '**/*$State.class',`

But in real project I still have the same problem:

`Caused by: java.io.FileNotFoundException: /Users/tse/jd/medialib/MediaLib/app/build/intermediates/classes/debug/ru/roscha_akademii/medialib/video/showlist/list/view/VideoListAdapter$MyViewHolder$show$inlined$let$lambda$1.class (No such file or directory)`
