### ISSUE TITLE
NoSuchFieldException: $jacocoAccess

### ISSUE THREAD

**Issue by grepx** [arturdm/jacoco-android-gradle-plugin#44]
Hi,
I've tried adding jacoco android to a barebones test project generated by the latest android studio and I'm getting the following crash when attempting to run the tests (either using `./gradlew jacocoTestReport` or when using just `./gradlew test`:

```
> Task :app:testDebugUnitTest FAILED
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:510)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:522)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
FATAL ERROR in native method: processing of -javaagent failed
        at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
        at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
        at org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.base/java.lang.Class.getField(Class.java:1958)
        at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
        ... 9 more
```
Not sure if this is a bug or if I'm just configuring it incorrectly? I uploaded my minimal implementation here if it helps:
https://github.com/grepx/JacocoNotWorking

Cheers,
Greg

**Comment by grepx** [comment]
I found the issue - I was using the Java 10 JDK, switched to Java 8 and it worked.

**Comment by himanshuganatra** [comment]
How can I fix this on Java 21, I am using jacoco version 0.8.11, official website says 0.8.11 supports Java 21
